name: getProducts
query: |-
    query getProducts {
      products(order_by: $order) {
        id
        name
        price
      }
    }
vars: |-
    {
      "include_user": false,
      "order": ""
    }
order:
    var: order
    values:
        - price_and_id
        - just_id
